# Do not remove this file
# (even though we are not using travis anymore)
# it is used a test matrix when running tests on the dev's machine

language: ruby

cache:
  bundler: true
  directories:
  - vendor/bundle

env:
  - DBTYPE=postgresql
  - DBTYPE=mysql2

rvm:
  - 3.1.0
  - 3.0.3
  - 2.7.5
  - 2.6.9
  - 2.5.9
#  - ruby-head
#  - jruby-9.0.5.0

gemfile:
  - gemfiles/libraries.gemfile
  - gemfiles/unit.gemfile
  - gemfiles/instrumentation_mocked.gemfile
  - gemfiles/instrumentation_mocked_oldgems.gemfile
  - gemfiles/frameworks.gemfile
  - gemfiles/rails70.gemfile
  - gemfiles/rails61.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/noop.gemfile
#  - gemfiles/profiling.gemfile

matrix:
  exclude:
    - rvm: 3.1.0
      gemfile: gemfiles/rails52.gemfile
    - rvm: 3.0.3
      gemfile: gemfiles/rails52.gemfile

    - rvm: 2.6.9
      gemfile: gemfiles/rails70.gemfile
    - rvm: 2.5.9
      gemfile: gemfiles/rails70.gemfile

    - gemfile: gemfiles/unit.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/noop.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/libraries.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/instrumentation_mocked.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/instrumentation_mocked_oldgems.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/frameworks.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/profiling.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/delayed_job.gemfile
      env: DBTYPE=mysql2
  allow_failures:
    - rvm: ruby-head
