name: Build docker images

on:
  push:
    paths:
    - 'test/run_tests/Dockerfile_*'
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/apm_ruby
  DOCKERFILE: test/run_tests/Dockerfile

jobs:

  build_push:
    name: Build docker images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, debian, centos, alpine]

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v1

    - name: Log in to the Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_${{ matrix.os }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: test/run_tests/Dockerfile_${{ matrix.os }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
