name: Verify Installation

on:
  workflow_dispatch:
    inputs:
      install-registry:
        required: true
        description: 'Registry used for install tests, e.g. RubyGem, packagecloud'
        type: choice
        default: 'RubyGem'
        options:
        - RubyGem
        - packagecloud

      solarwinds-version:
        required: true
        description: 'Solarwinds apm version'

env:
  SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}
  SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY_PROD }}
  SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR_PROD }}
  PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

jobs:

  verify_install_amd64_test:
    name: ruby - ${{ matrix.ruby_version }} - ${{ matrix.os }} amd64 - ${{ github.event.inputs.solarwinds-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, alpine]
        ruby_version: [3.1.0, 2.7.5]

    container:
      image: ghcr.io/${{ github.repository }}/apm_ruby_${{ matrix.os }}:nh-27837-b

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run install test
        working-directory: .github/workflows/
        run: ./scripts/_helper_run_install_tests.sh
        shell: sh
        env:
          MODE: ${{ github.event.inputs.install-registry }}
          ARCHITECTURE: AMD
          RUBY_VERSION: ${{ matrix.ruby_version }}


  verify_install_arm64_test:
    name: ruby - ${{ matrix.os }} arm64 - ${{ github.event.inputs.solarwinds-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # list of supported platform: https://github.com/uraimo/run-on-arch-action#supported-platforms
        os: [ubuntu, alpine]
        ruby_version: [3.1.0, 2.7.5]

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2

      - run: docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/apm_ruby_${{ matrix.os }}:nh-27837-b
      
      - name: Run tests in container using QEMU
        run: |
          sudo docker run \
            --platform linux/arm64 \
            -e SW_APM_SERVICE_KEY=${{ secrets.SW_APM_SERVICE_KEY }} \
            -e SW_APM_COLLECTOR=${{ secrets.SW_APM_COLLECTOR }} \
            -e SOLARWINDS_APM_VERSION=${{ github.event.inputs.solarwinds-version }} \
            -e PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }} \
            -e MODE=${{ github.event.inputs.install-registry }} \
            -e ARCHITECTURE=AMD \
            -e RUBY_VERSION=${{ matrix.ruby_version }} \
            -v $(pwd):/home \
            --rm ghcr.io/${{ github.repository }}/apm_ruby_${{ matrix.os }}:nh-27837-b \
            ./home/.github/workflows/scripts/_helper_run_install_tests.sh










